# Generated by Django 5.2.15 on 2026-07-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusiPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='试卷名称', help_text='试卷的唯一标识名称', max_length=200, verbose_name='试卷名称')),
                ('description', models.TextField(blank=True, db_comment='试卷描述（选填）', default='', help_text='试卷的补充说明（选填）', verbose_name='试卷描述')),
                ('total_score', models.DecimalField(db_comment='试卷满分，由关联题目分值汇总计算', decimal_places=2, default=0.0, help_text='试卷满分，由关联题目的分值自动汇总计算', max_digits=6, verbose_name='总分')),
                ('pass_score', models.DecimalField(db_comment='及格分数线，支持两位小数', decimal_places=2, default=60.0, help_text='达到此分数即为及格', max_digits=5, verbose_name='及格分数线')),
                ('duration_minutes', models.PositiveIntegerField(db_comment='考试时长，单位：分钟', default=60, help_text='整场考试允许的最长答题时间', verbose_name='考试时长（分钟）')),
                ('is_deleted', models.BooleanField(db_comment='软删除标记：1=已删除，0=正常', db_index=True, default=False, help_text='软删除标记', verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='试卷首次创建的时间', help_text='试卷首次创建的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='每次保存时自动更新为当前时间', help_text='试卷最后修改的时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'busi_papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusiPaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_comment='题目展示序号，数字越小越靠前', default=0, help_text='题目在试卷中的展示序号，数字越小越靠前', verbose_name='排序序号')),
                ('score', models.DecimalField(db_comment='本题在试卷中的分值，支持两位小数', decimal_places=2, help_text='该题在本试卷中的分值，支持两位小数（可覆盖题目的默认分值）', max_digits=5, verbose_name='本题分值')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='题目被添加到试卷的时间', help_text='题目被添加到试卷的时间', verbose_name='关联时间')),
            ],
            options={
                'verbose_name': '试卷-题目关联',
                'verbose_name_plural': '试卷-题目关联',
                'db_table': 'busi_paper_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusiPaperRandomRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveIntegerField(db_comment='随机抽取的题目数量', default=1, help_text='从该分类中随机抽取的题目数量', verbose_name='抽取数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='规则创建时间', help_text='规则创建的时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '随机抽题规则',
                'verbose_name_plural': '随机抽题规则',
                'db_table': 'busi_paper_random_rules',
            },
        ),
    ]
