# Generated by Django 5.2.15 on 2026-07-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='试卷的唯一标识名称', max_length=200, verbose_name='试卷名称')),
                ('description', models.TextField(blank=True, default='', help_text='试卷的补充说明（选填）', verbose_name='试卷描述')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, help_text='试卷满分，由关联题目的分值自动汇总计算', max_digits=6, verbose_name='总分')),
                ('pass_score', models.DecimalField(decimal_places=2, default=60.0, help_text='达到此分数即为及格', max_digits=5, verbose_name='及格分数线')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='整场考试允许的最长答题时间', verbose_name='考试时长（分钟）')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='软删除标记', verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='试卷首次创建的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='试卷最后修改的时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='题目在试卷中的展示序号，数字越小越靠前', verbose_name='排序序号')),
                ('score', models.DecimalField(decimal_places=2, help_text='该题在本试卷中的分值，支持两位小数（可覆盖题目的默认分值）', max_digits=5, verbose_name='本题分值')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='题目被添加到试卷的时间', verbose_name='关联时间')),
            ],
            options={
                'verbose_name': '试卷-题目关联',
                'verbose_name_plural': '试卷-题目关联',
                'db_table': 'paper_questions',
                'ordering': ['order'],
            },
        ),
    ]
