# Generated by Django 5.2.15 on 2026-07-09 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='busipaper',
            name='created_by',
            field=models.ForeignKey(db_comment='出卷人用户ID', help_text='创建该试卷的教师或管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_papers', to=settings.AUTH_USER_MODEL, verbose_name='出卷人'),
        ),
        migrations.AddField(
            model_name='busipaperquestion',
            name='paper',
            field=models.ForeignKey(db_comment='所属试卷ID', help_text='关联的试卷', on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='papers.busipaper', verbose_name='所属试卷'),
        ),
        migrations.AddField(
            model_name='busipaperquestion',
            name='question',
            field=models.ForeignKey(db_comment='关联的题目ID', help_text='关联的题目', on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='questions.busiquestion', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='busipaper',
            name='questions',
            field=models.ManyToManyField(db_comment='试卷包含的题目，通过中间表关联', help_text='试卷包含的题目，通过 PaperQuestion 中间表关联', related_name='papers', through='papers.BusiPaperQuestion', to='questions.busiquestion', verbose_name='题目列表'),
        ),
        migrations.AddField(
            model_name='busipaperrandomrule',
            name='category',
            field=models.ForeignKey(db_comment='题目分类ID', help_text='从哪个题目分类中随机抽取', on_delete=django.db.models.deletion.CASCADE, related_name='random_rules', to='questions.busiquestioncategory', verbose_name='抽取分类'),
        ),
        migrations.AddField(
            model_name='busipaperrandomrule',
            name='paper',
            field=models.ForeignKey(db_comment='所属试卷ID', help_text='应用此规则的试卷', on_delete=django.db.models.deletion.CASCADE, related_name='random_rules', to='papers.busipaper', verbose_name='所属试卷'),
        ),
        migrations.AlterUniqueTogether(
            name='busipaperquestion',
            unique_together={('paper', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='busipaperrandomrule',
            unique_together={('paper', 'category')},
        ),
    ]
