# Generated by Django 5.2.15 on 2026-07-03 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='created_by',
            field=models.ForeignKey(help_text='创建该试卷的教师或管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_papers', to=settings.AUTH_USER_MODEL, verbose_name='出卷人'),
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='paper',
            field=models.ForeignKey(help_text='关联的试卷', on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='papers.paper', verbose_name='所属试卷'),
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='question',
            field=models.ForeignKey(help_text='关联的题目', on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='questions.question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='paper',
            name='questions',
            field=models.ManyToManyField(help_text='试卷包含的题目，通过 PaperQuestion 中间表关联', related_name='papers', through='papers.PaperQuestion', to='questions.question', verbose_name='题目列表'),
        ),
        migrations.AlterUniqueTogether(
            name='paperquestion',
            unique_together={('paper', 'question')},
        ),
    ]
