# Generated by Django 5.2.15 on 2026-07-04 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_initial'),
        ('questions', '0003_add_db_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='试卷首次创建的时间', help_text='试卷首次创建的时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='created_by',
            field=models.ForeignKey(db_comment='出卷人用户ID', help_text='创建该试卷的教师或管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_papers', to=settings.AUTH_USER_MODEL, verbose_name='出卷人'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(blank=True, db_comment='试卷描述（选填）', default='', help_text='试卷的补充说明（选填）', verbose_name='试卷描述'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='duration_minutes',
            field=models.PositiveIntegerField(db_comment='考试时长，单位：分钟', default=60, help_text='整场考试允许的最长答题时间', verbose_name='考试时长（分钟）'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='is_deleted',
            field=models.BooleanField(db_comment='软删除标记：1=已删除，0=正常', db_index=True, default=False, help_text='软删除标记', verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(db_comment='试卷名称', help_text='试卷的唯一标识名称', max_length=200, verbose_name='试卷名称'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pass_score',
            field=models.DecimalField(db_comment='及格分数线，支持两位小数', decimal_places=2, default=60.0, help_text='达到此分数即为及格', max_digits=5, verbose_name='及格分数线'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='questions',
            field=models.ManyToManyField(db_comment='试卷包含的题目，通过中间表关联', help_text='试卷包含的题目，通过 PaperQuestion 中间表关联', related_name='papers', through='papers.PaperQuestion', to='questions.question', verbose_name='题目列表'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='total_score',
            field=models.DecimalField(db_comment='试卷满分，由关联题目分值汇总计算', decimal_places=2, default=0.0, help_text='试卷满分，由关联题目的分值自动汇总计算', max_digits=6, verbose_name='总分'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='每次保存时自动更新为当前时间', help_text='试卷最后修改的时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='paperquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='题目被添加到试卷的时间', help_text='题目被添加到试卷的时间', verbose_name='关联时间'),
        ),
        migrations.AlterField(
            model_name='paperquestion',
            name='order',
            field=models.PositiveIntegerField(db_comment='题目展示序号，数字越小越靠前', default=0, help_text='题目在试卷中的展示序号，数字越小越靠前', verbose_name='排序序号'),
        ),
        migrations.AlterField(
            model_name='paperquestion',
            name='paper',
            field=models.ForeignKey(db_comment='所属试卷ID', help_text='关联的试卷', on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='papers.paper', verbose_name='所属试卷'),
        ),
        migrations.AlterField(
            model_name='paperquestion',
            name='question',
            field=models.ForeignKey(db_comment='关联的题目ID', help_text='关联的题目', on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='questions.question', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='paperquestion',
            name='score',
            field=models.DecimalField(db_comment='本题在试卷中的分值，支持两位小数', decimal_places=2, help_text='该题在本试卷中的分值，支持两位小数（可覆盖题目的默认分值）', max_digits=5, verbose_name='本题分值'),
        ),
    ]
