"""
Django settings for 在线考试系统 (Online Exam System).

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

import dotenv

# ============================================
# 基础路径和环境变量
# ============================================
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 环境变量
dotenv.load_dotenv(BASE_DIR / '.env')

# ============================================
# 安全配置
# ============================================
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-this-in-production!!!')

DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# ============================================
# 应用注册
# ============================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方库
    'rest_framework',                    # Django REST Framework
    'corsheaders',                       # 跨域支持
    'rest_framework_simplejwt',          # JWT 认证
    'rest_framework_simplejwt.token_blacklist',  # JWT 黑名单（支持登出）
    'django_filters',                    # 过滤支持
    'drf_spectacular',                   # API 文档自动生成

    # 自定义应用
    'apps.users',                       # 用户模块
    'apps.questions',                   # 题库模块
    'apps.papers',                      # 试卷模块
    'apps.exams',                       # 考试模块
]

# ============================================
# 中间件配置
# ============================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',     # CORS 中间件（尽量靠前）
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ============================================
# 数据库配置
# 开发环境使用 SQLite，生产环境使用 MariaDB
# 设置环境变量 USE_SQLITE=false 切换到 MariaDB
# ============================================
USE_SQLITE = os.getenv('USE_SQLITE', 'true').lower() in ('true', '1', 'yes')

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'exam_system'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }

# ============================================
# 密码验证
# ============================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================
# 国际化和时区
# ============================================
LANGUAGE_CODE = 'zh-hans'              # 中文简体
TIME_ZONE = 'Asia/Shanghai'            # 上海时区（UTC+8）
USE_I18N = True
USE_TZ = True                          # 数据库存储 UTC，显示时自动转换

# ============================================
# 静态文件和媒体文件
# ============================================
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================
# 默认主键类型
# ============================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# 自定义用户模型
# 重要：必须在第一次 migrate 之前设置，否则会导致兼容问题
AUTH_USER_MODEL = 'users.BusiUser'

# ============================================
# Django REST Framework 配置
# ============================================
REST_FRAMEWORK = {
    # 默认认证类：JWT 认证
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # 默认权限类：需认证才能访问
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # API 文档 Schema 类
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # 默认分页类
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,                               # 每页默认 20 条

    # 默认过滤后端
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),

    # 默认渲染器（JSON）
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        # 开发环境启用 BrowsableAPIRenderer 方便调试
        'rest_framework.renderers.BrowsableAPIRenderer' if DEBUG
        else 'rest_framework.renderers.JSONRenderer',
    ),

    # 默认解析器
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',  # 支持文件上传
    ),

    # 异常处理（统一返回格式）
    'EXCEPTION_HANDLER': 'utils.exceptions.custom_exception_handler',

    # 日期时间格式
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}

# ============================================
# Simple JWT 配置
# ============================================
SIMPLE_JWT = {
    # Token 有效期
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', 60))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME_DAYS', 7))
    ),

    # 是否自动刷新 Token
    'ROTATE_REFRESH_TOKENS': True,
    # 刷新后旧 Token 加入黑名单
    'BLACKLIST_AFTER_ROTATION': True,

    # 更新 Token 的最后登录时间
    'UPDATE_LAST_LOGIN': True,

    # 签名算法
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,

    # 认证头类型
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    # Token 中包含的用户字段
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Token 类型声明
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',                          # JWT ID（用于黑名单）

    # 滑动过期（每次请求自动续期）
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=60),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}

# ============================================
# CORS 跨域配置
# ============================================
# 允许的跨域来源
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',')

# 允许所有来源时使用（开发环境）
CORS_ALLOW_ALL_ORIGINS = DEBUG

# 允许携带 Cookie（跨域认证时需要）
CORS_ALLOW_CREDENTIALS = True

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 允许的请求方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ============================================
# DRF Spectacular (API 文档) 配置
# ============================================
SPECTACULAR_SETTINGS = {
    'TITLE': '在线考试系统 API',
    'DESCRIPTION': '在线考试系统后端接口文档',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# ============================================
# 日志配置
# ============================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'debug.log',
            'maxBytes': 10 * 1024 * 1024,          # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
