# Generated by Django 5.2.15 on 2026-07-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busiuser',
            name='business_scope',
            field=models.CharField(blank=True, db_comment='分管业务范围', default='', help_text='资产(asset)/负债(liability)/两者(both)/零售(retail)', max_length=20, verbose_name='分管业务'),
        ),
        migrations.AddField(
            model_name='busiuser',
            name='org_nm',
            field=models.CharField(blank=True, db_comment='所属村行/中心支行名称', default='', help_text='村行或中心支行名称', max_length=100, verbose_name='所属机构'),
        ),
    ]
