# Generated by Django 5.2.15 on 2026-07-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='记录首次创建的时间，创建后不再自动更新', help_text='账号首次创建的时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_comment='软删除标记：1=已删除，0=正常', db_index=True, default=False, help_text='软删除标记：True=已删除(不可见)，False=正常', verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('teacher', '教师'), ('student', '学生')], db_comment='用户角色：admin=管理员, teacher=教师, student=学生', default='student', help_text='用户角色：管理员(admin)/教师(teacher)/学生(student)', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='每次保存时自动更新为当前时间', help_text='账号最后修改的时间', verbose_name='更新时间'),
        ),
    ]
