# Generated by Django 5.2.15 on 2026-07-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_english_to_chinese_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='busiuser',
            name='password_changed',
            field=models.BooleanField(db_comment='是否已修改初始密码：1=已改，0=未改', default=True, help_text='用户首次登录后是否已修改初始密码', verbose_name='已修改密码'),
        ),
        migrations.AlterField(
            model_name='busiuser',
            name='business_scope',
            field=models.JSONField(blank=True, db_comment='分管业务范围（JSON数组）', default=list, help_text='["asset"]=资产 ["liability"]=负债 ["asset","liability"]=两者 ["retail"]=零售', verbose_name='分管业务'),
        ),
        migrations.AlterField(
            model_name='busiuser',
            name='position',
            field=models.CharField(blank=True, db_comment='岗位名称', default='', help_text='行长/副行长/业务部负责人等', max_length=50, verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='busiuser',
            name='remark',
            field=models.TextField(blank=True, db_comment='备注信息', default='', help_text='补充说明', verbose_name='备注'),
        ),
    ]
