# Generated by Django 5.2.15 on 2026-07-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_busiuser_password_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busiuser',
            name='org_no',
            field=models.CharField(blank=True, db_comment='机构编号', default='', help_text='机构的唯一编号', max_length=20, verbose_name='机构号'),
        ),
    ]
