# Generated by Django 5.2.15 on 2026-08-03 02:24

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_busiuser_business_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busiuser',
            name='business_scope',
            field=utils.fields.ChineseJSONField(blank=True, db_comment='分管业务范围（JSON数组）', default=list, help_text='["asset"]=资产 ["liability"]=负债 ["asset","liability"]=两者 ["retail"]=零售', verbose_name='分管业务'),
        ),
        migrations.AlterField(
            model_name='busiuser',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('teacher', '评委'), ('student', '考生')], db_comment='用户角色：admin=管理员, teacher=教师, student=学生', default='student', help_text='用户角色：管理员(admin)/教师(teacher)/学生(student)', max_length=20, verbose_name='角色'),
        ),
    ]
