# Generated by Django 5.2.15 on 2026-07-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('true_false', '判断题'), ('fill_blank', '填空题'), ('short_answer', '简答题')], help_text='single_choice/multiple_choice/true_false/fill_blank/short_answer', max_length=20, verbose_name='题目类型')),
                ('content', models.TextField(help_text='题目的文字描述，支持 Markdown 格式', verbose_name='题干内容')),
                ('options', models.JSONField(blank=True, default=list, help_text='JSON数组，如 ["A. 北京", "B. 上海"]，仅选择题需要', verbose_name='选项列表')),
                ('correct_answer', models.JSONField(help_text='单选存字符串"A"，多选存数组["A","C"]，判断存"对"/"错"，填空简答存字符串', verbose_name='正确答案')),
                ('analysis', models.TextField(blank=True, default='', help_text='对正确答案的详细解释，学生查看成绩时展示（选填）', verbose_name='答案解析')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', help_text='easy=简单，medium=中等，hard=困难', max_length=10, verbose_name='难度等级')),
                ('default_score', models.DecimalField(decimal_places=2, default=5.0, help_text='题目的默认分数，支持两位小数，在试卷中可被覆盖', max_digits=5, verbose_name='默认分值')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='软删除标记：True=已删除，False=正常', verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='题目首次创建的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='题目最后修改的时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类的唯一标识名称，如"计算机基础"', max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, default='', help_text='分类的详细说明（选填）', verbose_name='分类描述')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='软删除标记：True=已删除，False=正常', verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录首次创建的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后修改的时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题目分类',
                'verbose_name_plural': '题目分类',
                'db_table': 'question_categories',
                'ordering': ['name'],
            },
        ),
    ]
