# Generated by Django 5.2.15 on 2026-07-09 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='busiquestion',
            name='created_by',
            field=models.ForeignKey(db_comment='出题人用户ID', help_text='出题人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='busiquestioncategory',
            name='created_by',
            field=models.ForeignKey(db_comment='创建人用户ID', help_text='创建该分类的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_categories', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='busiquestion',
            name='category',
            field=models.ForeignKey(blank=True, db_comment='所属分类ID，外键关联question_categories表', help_text='题目归入的分类，便于管理和筛选', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.busiquestioncategory', verbose_name='所属分类'),
        ),
        migrations.AddIndex(
            model_name='busiquestion',
            index=models.Index(fields=['question_type'], name='idx_question_type'),
        ),
        migrations.AddIndex(
            model_name='busiquestion',
            index=models.Index(fields=['difficulty'], name='idx_difficulty'),
        ),
        migrations.AddIndex(
            model_name='busiquestion',
            index=models.Index(fields=['category'], name='idx_category'),
        ),
    ]
