# Generated by Django 5.2.15 on 2026-07-03 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(help_text='出题人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='created_by',
            field=models.ForeignKey(help_text='创建该分类的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_categories', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, help_text='题目归入的分类，便于管理和筛选', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.questioncategory', verbose_name='所属分类'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='idx_question_type'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='idx_difficulty'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='idx_category'),
        ),
    ]
