# Generated by Django 5.2.15 on 2026-08-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busiquestion',
            name='data_dt',
            field=models.CharField(blank=True, db_comment='数据月份，如202607', help_text='导入指标题库时的数据月份，如 202607', max_length=10, null=True, verbose_name='数据月份'),
        ),
    ]
