# Generated by Django 5.2.15 on 2026-07-04 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='analysis',
            field=models.TextField(blank=True, db_comment='答案解析，学生查看成绩时展示', default='', help_text='对正确答案的详细解释，学生查看成绩时展示（选填）', verbose_name='答案解析'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, db_comment='所属分类ID，外键关联question_categories表', help_text='题目归入的分类，便于管理和筛选', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.questioncategory', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(db_comment='题干文字内容，支持Markdown格式', help_text='题目的文字描述，支持 Markdown 格式', verbose_name='题干内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(db_comment='正确答案：单选/判断存字符串，多选存JSON数组，填空/简答存字符串', help_text='单选存字符串"A"，多选存数组["A","C"]，判断存"对"/"错"，填空简答存字符串', verbose_name='正确答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='题目首次创建的时间', help_text='题目首次创建的时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(db_comment='出题人用户ID', help_text='出题人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='question',
            name='default_score',
            field=models.DecimalField(db_comment='题目默认分值，支持两位小数，试卷中可覆盖', decimal_places=2, default=5.0, help_text='题目的默认分数，支持两位小数，在试卷中可被覆盖', max_digits=5, verbose_name='默认分值'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], db_comment='难度等级：easy=简单, medium=中等, hard=困难', default='medium', help_text='easy=简单，medium=中等，hard=困难', max_length=10, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(db_comment='软删除标记：1=已删除，0=正常', db_index=True, default=False, help_text='软删除标记：True=已删除，False=正常', verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, db_comment='JSON数组格式的选项列表，仅选择题使用', default=list, help_text='JSON数组，如 ["A. 北京", "B. 上海"]，仅选择题需要', verbose_name='选项列表'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('true_false', '判断题'), ('fill_blank', '填空题'), ('short_answer', '简答题')], db_comment='题目类型：single_choice=单选, multiple_choice=多选, true_false=判断, fill_blank=填空, short_answer=简答', help_text='single_choice/multiple_choice/true_false/fill_blank/short_answer', max_length=20, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='每次保存时自动更新为当前时间', help_text='题目最后修改的时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='记录首次创建的时间', help_text='记录首次创建的时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='created_by',
            field=models.ForeignKey(db_comment='创建人用户ID', help_text='创建该分类的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_categories', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='description',
            field=models.TextField(blank=True, db_comment='分类描述（选填）', default='', help_text='分类的详细说明（选填）', verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='is_deleted',
            field=models.BooleanField(db_comment='软删除标记：1=已删除，0=正常', db_index=True, default=False, help_text='软删除标记：True=已删除，False=正常', verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(db_comment='分类名称，唯一', help_text='分类的唯一标识名称，如"计算机基础"', max_length=100, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='每次保存时自动更新为当前时间', help_text='记录最后修改的时间', verbose_name='更新时间'),
        ),
    ]
