# Generated by Django 5.2.15 on 2026-07-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如"2024年期末考试"', max_length=200, verbose_name='考试名称')),
                ('start_time', models.DateTimeField(help_text='在此时间之后学生才能进入考试', verbose_name='考试开始时间')),
                ('end_time', models.DateTimeField(help_text='到达此时间后自动提交未交卷的考试', verbose_name='考试结束时间')),
                ('status', models.CharField(choices=[('upcoming', '未开始'), ('ongoing', '进行中'), ('finished', '已结束')], default='upcoming', help_text='upcoming=未开始，ongoing=进行中，finished=已结束', max_length=20, verbose_name='考试状态')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='软删除标记', verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='考试首次发布的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='考试信息最后修改的时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试场次',
                'verbose_name_plural': '考试场次',
                'db_table': 'exam_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '答题中'), ('submitted', '已提交'), ('auto_submitted', '时间到自动提交')], default='not_started', help_text='not_started=未开始，in_progress=答题中，submitted=已提交，auto_submitted=超时自动提交', max_length=20, verbose_name='提交状态')),
                ('start_time', models.DateTimeField(blank=True, help_text='学生点击"开始考试"的时间', null=True, verbose_name='开始答题时间')),
                ('submit_time', models.DateTimeField(blank=True, help_text='学生点击"交卷"或系统自动提交的时间', null=True, verbose_name='实际提交时间')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='整场考试的实际得分，由各题得分汇总计算', max_digits=6, null=True, verbose_name='考试总分')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除标记', verbose_name='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='提交记录首次创建的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='提交记录最后修改的时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试提交记录',
                'verbose_name_plural': '考试提交记录',
                'db_table': 'exam_submissions',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, help_text='单选/判断存字符串，多选存数组，填空/简答存字符串', null=True, verbose_name='学生答案')),
                ('is_correct', models.BooleanField(blank=True, help_text='True=正确，False=错误，None=主观题待批改', null=True, verbose_name='是否回答正确')),
                ('score_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='该题学生获得的分数，0分为打错，NULL为未批改', max_digits=5, null=True, verbose_name='实际得分')),
                ('status', models.CharField(choices=[('draft', '暂存'), ('submitted', '已提交'), ('graded', '已批改')], default='draft', help_text='draft=暂存（未提交），submitted=已提交，graded=已批改', max_length=20, verbose_name='答题状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='答题记录首次创建的时间', verbose_name='首次保存时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='答案最后保存的时间', verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '学生答题记录',
                'verbose_name_plural': '学生答题记录',
                'db_table': 'student_answers',
            },
        ),
    ]
