# Generated by Django 5.2.15 on 2026-07-03 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='created_by',
            field=models.ForeignKey(help_text='发布该考试的教师或管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='paper',
            field=models.ForeignKey(help_text='本次考试使用的试卷', on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='papers.paper', verbose_name='试卷'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='为空则开放给所有学生参加', related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='指定参考学生'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='exam_session',
            field=models.ForeignKey(help_text='所属的考试', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.examsession', verbose_name='考试场次'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='student',
            field=models.ForeignKey(help_text='提交考试的学生', on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='exam_session',
            field=models.ForeignKey(help_text='所属的考试', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exams.examsession', verbose_name='考试场次'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='paper_question',
            field=models.ForeignKey(help_text='对应的试卷题目及其分值', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='papers.paperquestion', verbose_name='试卷题目'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(help_text='答题的学生', on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('exam_session', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['exam_session', 'student'], name='idx_exam_student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('exam_session', 'student', 'paper_question')},
        ),
    ]
