# Generated by Django 5.2.15 on 2026-07-04 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
        ('papers', '0003_add_db_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='考试首次发布的时间', help_text='考试首次发布的时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='created_by',
            field=models.ForeignKey(db_comment='发布人用户ID', help_text='发布该考试的教师或管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='end_time',
            field=models.DateTimeField(db_comment='考试结束时间，到达后自动提交', help_text='到达此时间后自动提交未交卷的考试', verbose_name='考试结束时间'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='is_deleted',
            field=models.BooleanField(db_comment='软删除标记：1=已删除，0=正常', db_index=True, default=False, help_text='软删除标记', verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='name',
            field=models.CharField(db_comment='考试名称', help_text='如"2024年期末考试"', max_length=200, verbose_name='考试名称'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='paper',
            field=models.ForeignKey(db_comment='考试使用的试卷ID', help_text='本次考试使用的试卷', on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='papers.paper', verbose_name='试卷'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='start_time',
            field=models.DateTimeField(db_comment='考试开始时间', help_text='在此时间之后学生才能进入考试', verbose_name='考试开始时间'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('upcoming', '未开始'), ('ongoing', '进行中'), ('finished', '已结束')], db_comment='考试状态：upcoming=未开始, ongoing=进行中, finished=已结束', default='upcoming', help_text='upcoming=未开始，ongoing=进行中，finished=已结束', max_length=20, verbose_name='考试状态'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='students',
            field=models.ManyToManyField(blank=True, db_comment='指定参考学生（为空则所有人可参加）', help_text='为空则开放给所有学生参加', related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='指定参考学生'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='每次保存时自动更新为当前时间', help_text='考试信息最后修改的时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='提交记录首次创建的时间', help_text='提交记录首次创建的时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='exam_session',
            field=models.ForeignKey(db_comment='所属考试场次ID', help_text='所属的考试', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.examsession', verbose_name='考试场次'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='is_deleted',
            field=models.BooleanField(db_comment='软删除标记：1=已删除，0=正常', default=False, help_text='软删除标记', verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='start_time',
            field=models.DateTimeField(blank=True, db_comment='学生点击开始考试的时间', help_text='学生点击"开始考试"的时间', null=True, verbose_name='开始答题时间'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('in_progress', '答题中'), ('submitted', '已提交'), ('auto_submitted', '时间到自动提交')], db_comment='提交状态：not_started=未开始, in_progress=答题中, submitted=已提交, auto_submitted=超时自动提交', default='not_started', help_text='not_started=未开始，in_progress=答题中，submitted=已提交，auto_submitted=超时自动提交', max_length=20, verbose_name='提交状态'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='student',
            field=models.ForeignKey(db_comment='提交考试的学生用户ID', help_text='提交考试的学生', on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='submit_time',
            field=models.DateTimeField(blank=True, db_comment='实际提交或自动提交的时间', help_text='学生点击"交卷"或系统自动提交的时间', null=True, verbose_name='实际提交时间'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='total_score',
            field=models.DecimalField(blank=True, db_comment='考试实际总分，由各题得分汇总', decimal_places=2, help_text='整场考试的实际得分，由各题得分汇总计算', max_digits=6, null=True, verbose_name='考试总分'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='每次保存时自动更新为当前时间', help_text='提交记录最后修改的时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.JSONField(blank=True, db_comment='学生提交的答案（JSON格式）', help_text='单选/判断存字符串，多选存数组，填空/简答存字符串', null=True, verbose_name='学生答案'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='答题记录首次创建的时间', help_text='答题记录首次创建的时间', verbose_name='首次保存时间'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='exam_session',
            field=models.ForeignKey(db_comment='所属考试场次ID', help_text='所属的考试', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exams.examsession', verbose_name='考试场次'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, db_comment='是否正确：1=正确, 0=错误, NULL=待批改', help_text='True=正确，False=错误，None=主观题待批改', null=True, verbose_name='是否回答正确'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='paper_question',
            field=models.ForeignKey(db_comment='对应的试卷题目ID', help_text='对应的试卷题目及其分值', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='papers.paperquestion', verbose_name='试卷题目'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='score_obtained',
            field=models.DecimalField(blank=True, db_comment='该题实际得分，支持两位小数', decimal_places=2, help_text='该题学生获得的分数，0分为打错，NULL为未批改', max_digits=5, null=True, verbose_name='实际得分'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='status',
            field=models.CharField(choices=[('draft', '暂存'), ('submitted', '已提交'), ('graded', '已批改')], db_comment='答题状态：draft=暂存, submitted=已提交, graded=已批改', default='draft', help_text='draft=暂存（未提交），submitted=已提交，graded=已批改', max_length=20, verbose_name='答题状态'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(db_comment='答题学生用户ID', help_text='答题的学生', on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='答案最后保存的时间', help_text='答案最后保存的时间', verbose_name='最后更新时间'),
        ),
    ]
