# Generated by Django 5.2.15 on 2026-07-29 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='busiexamsubmission',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, db_comment='调整浮动分的教师用户ID', help_text='调整浮动分的教师', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_scores', to=settings.AUTH_USER_MODEL, verbose_name='调分人'),
        ),
        migrations.AddField(
            model_name='busiexamsubmission',
            name='float_score',
            field=models.DecimalField(blank=True, db_comment='浮动分（实效附加评价项）', decimal_places=2, help_text='由评委在基础分之上加减的实效附加评价分', max_digits=5, null=True, verbose_name='浮动分'),
        ),
        migrations.AddField(
            model_name='busiexamsubmission',
            name='float_score_reason',
            field=models.TextField(blank=True, db_comment='浮动分评定依据说明', default='', help_text='评委填写浮动分的依据说明（选填）', verbose_name='浮动分评定依据'),
        ),
        migrations.CreateModel(
            name='ExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_score_enabled', models.BooleanField(db_comment='浮动分开关', default=False, help_text='是否允许评委在基础分上加减浮动分', verbose_name='启用浮动分')),
                ('float_score_min', models.IntegerField(db_comment='浮动分下限', default=-10, help_text='浮动分最小值（如-10）', verbose_name='浮动分下限')),
                ('float_score_max', models.IntegerField(db_comment='浮动分上限', default=10, help_text='浮动分最大值（如+10）', verbose_name='浮动分上限')),
                ('multi_paper_enabled', models.BooleanField(db_comment='多套卷开关', default=False, help_text='是否动态生成多套试卷并随机分配', verbose_name='启用多套卷')),
                ('paper_count', models.IntegerField(db_comment='多套卷生成的试卷数量', default=3, help_text='启用多套卷时生成的试卷套数', verbose_name='试卷套数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam_session', models.OneToOneField(db_comment='关联的考试场次ID', help_text='关联的考试', on_delete=django.db.models.deletion.CASCADE, related_name='config', to='exams.busiexamsession', verbose_name='考试场次')),
            ],
            options={
                'verbose_name': '考试扩展配置',
                'verbose_name_plural': '考试扩展配置',
                'db_table': 'exam_configs',
            },
        ),
    ]
