# Generated by Django 5.2.15 on 2026-07-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_busiexamsubmission_adjusted_by_and_more'),
        ('papers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busiexamsession',
            name='papers',
            field=models.ManyToManyField(blank=True, help_text='启用多套卷时关联的试卷集合', related_name='multi_exam_sessions', to='papers.busipaper', verbose_name='多套试卷'),
        ),
    ]
