# Generated by Django 5.2.15 on 2026-07-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_busiexamsession_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='busiexamsubmission',
            name='adjusted_at',
            field=models.DateTimeField(blank=True, db_comment='浮动分调整时间', help_text='最后一次调整浮动分的时间', null=True, verbose_name='浮动分调整时间'),
        ),
    ]
