# Generated by Django 5.2.15 on 2026-07-31 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_busiexamsubmission_adjusted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examconfig',
            name='multi_paper_enabled',
        ),
        migrations.RemoveField(
            model_name='examconfig',
            name='paper_count',
        ),
        migrations.AddField(
            model_name='busiexamsubmission',
            name='drawn_question_ids',
            field=models.JSONField(blank=True, db_comment='考生抽取的题目ID列表（JSON数组）', default=list, help_text='考生开考时随机抽取的题目ID数组，用于恢复进度', verbose_name='抽题记录'),
        ),
        migrations.AlterField(
            model_name='examconfig',
            name='float_score_enabled',
            field=models.BooleanField(default=False, verbose_name='启用浮动分'),
        ),
        migrations.AlterField(
            model_name='examconfig',
            name='float_score_max',
            field=models.IntegerField(default=10, verbose_name='浮动分上限'),
        ),
        migrations.AlterField(
            model_name='examconfig',
            name='float_score_min',
            field=models.IntegerField(default=-10, verbose_name='浮动分下限'),
        ),
        migrations.CreateModel(
            name='ExamRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=30, verbose_name='题型')),
                ('count', models.IntegerField(default=0, verbose_name='抽题数量')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='分类筛选')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_session', models.ForeignKey(db_comment='关联的考试场次ID', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='exams.busiexamsession', verbose_name='考试场次')),
            ],
            options={
                'verbose_name': '考试抽题规则',
                'verbose_name_plural': '考试抽题规则',
                'db_table': 'exam_rules',
                'unique_together': {('exam_session', 'question_type')},
            },
        ),
    ]
