# Generated by Django 5.2.15 on 2026-07-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_examconfig_multi_paper_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busiexamsession',
            name='exam_scope',
            field=models.JSONField(blank=True, db_comment='考试业务范围（JSON数组）', default=list, help_text='从抽题分类名中提取的前缀集合，如["资产","负债"]，用于匹配考生分管业务', verbose_name='考试业务范围'),
        ),
    ]
