# Generated by Django 5.2.15 on 2026-08-03 01:04

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_busiexamsession_exam_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busiexamsession',
            name='exam_scope',
            field=utils.fields.ChineseJSONField(blank=True, db_comment='考试业务范围（JSON数组）', default=list, help_text='从抽题分类名中提取的前缀集合，如["资产","负债"]，用于匹配考生分管业务', verbose_name='考试业务范围'),
        ),
    ]
