# Generated by Django 5.2.15 on 2026-08-04 09:29

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_busiexamsession_exam_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrule',
            name='data_dt',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='数据日期'),
        ),
        migrations.AddField(
            model_name='examrule',
            name='question_source',
            field=models.CharField(db_comment='题目来源：regular=常规题库, data=数据指标题', default='regular', help_text='regular=常规题库, data=数据指标题', max_length=10, verbose_name='题目来源'),
        ),
        migrations.CreateModel(
            name='BusiDataQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_no', models.CharField(db_comment='机构号，考生抽题时按此匹配', max_length=20, verbose_name='机构号')),
                ('data_dt', models.CharField(db_comment='数据月份，格式YYYYMM', max_length=6, verbose_name='数据日期')),
                ('question_stem', models.TextField(db_comment='table+label+busi+col拼接', verbose_name='题干')),
                ('correct_answer', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='正确答案')),
                ('options', utils.fields.ChineseJSONField(default=list, help_text='4个选项的JSON数组，已随机打乱', verbose_name='选项列表')),
                ('num_fmt', models.CharField(default='3', max_length=5, verbose_name='数值格式')),
                ('table_name', models.CharField(default='', max_length=200, verbose_name='表名')),
                ('label_type', models.CharField(default='', max_length=100, verbose_name='标签类型')),
                ('busi_type', models.CharField(default='', max_length=100, verbose_name='业务类型')),
                ('col_nm', models.CharField(default='', max_length=100, verbose_name='列名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '数据指标题',
                'verbose_name_plural': '数据指标题',
                'db_table': 'busi_data_questions',
                'unique_together': {('org_no', 'data_dt', 'question_stem')},
            },
        ),
    ]
