# Generated by Django 5.2.15 on 2026-08-04 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_examrule_data_dt_examrule_question_source_and_more'),
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busidataquestion',
            name='question',
            field=models.ForeignKey(blank=True, db_comment='对应的BusiQuestion记录ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.busiquestion', verbose_name='关联题目'),
        ),
    ]
