# Generated by Django 5.2.15 on 2026-08-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_busidataquestion_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusiDataQuestion',
        ),
    ]
